export enum EventReason {
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    MESSAGE_CREATED = 'MESSAGE_CREATED',
    MESSAGE_UPDATED = 'MESSAGE_UPDATED',
    MESSAGE_DELETED = 'MESSAGE_DELETED',
}
