export enum EventReason {
    USER_CREATED = 'USER_CREATED',
    USER_UPDATED = 'USER_UPDATED',
    USER_DELETED = 'USER_DELETED',
    USER_DELETED_BY_ADMIN = 'USER_DELETED_BY_ADMIN',
    MEMBER_UPDATE = 'MEMBER_UPDATE',
    ROLE_CHANGE = 'ROLE_CHANGE',
    MESSAGE_CREATED = 'MESSAGE_CREATED',
    MESSAGE_UPDATED = 'MESSAGE_UPDATED',
    MESSAGE_DELETED = 'MESSAGE_DELETED',
}
